models/Administrator.php
<?php

namespace app\models;

use yii;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\behaviors\SluggableBehavior;

/**
 * This is the model class for table "administrator".
 *
 * @property integer $id
 * @property string $name
 * @property string $surname
 * @property string $slug
 * @property integer $company_id
 * @property string $email
 * @property string $auth_key
 * @property string $password_reset_token_hash
 * @property string $password_hash
 * @property string $group_role
 * @property string $status
 */
class Administrator extends ActiveRecord implements IdentityInterface
{
    const STATUS_BLOCKED = -1;
    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'administrator';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'surname', 'email', 'password_hash'], 'required'],
            [['company_id', 'status'], 'integer'],
            [['name', 'surname', 'slug', 'email', 'auth_key', 'password_reset_token_hash', 'password_hash', 'group_role'], 'string', 'max' => 255],
            [['email'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'group_role' => 'Role',
            'status' => 'Status active',
            'name' => 'Name',
            'surname' => 'Surname',
            'slug' => 'Slug',
            'company_id' => 'Company ID',
            'email' => 'Email',
            'password_hash' => 'Password',
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::className(),
                'attribute' => ['name', 'surname'],
                'ensureUnique' => true,
                //'slugAttribute' => 'slug',
            ],
        ];
    }

    public function setCompanyId($id)
    {
        $this->company_id = $id;
    }

    public function setCompanyIdRandom()
    {
        $companiesCount = Companies::find()->count();
        if ($companiesCount == 0)
            return null;
        $randomId = rand(1, $companiesCount);
        $this->company_id = $randomId;
    }

    public function setPassword($password)
    {
        $this->password_hash = self::encodePassword($password);
    }

    public function deleteCompany()
    {
        $this->company_id = null;
    }

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->auth_key = Yii::$app->getSecurity()->generateRandomString();
                $this->setPasswordResetToken();
                $this->status = self::STATUS_INACTIVE;
            }
            
            return true;
        } else {
            return false;
        }
    }

    public function setRoleAdmin($id)
    {
        $role = Yii::$app->authManager->getRole('admin');
        Yii::$app->authManager->assign($role, $id);
    }

    public function setRoleRoot($id)
    {
        $role = Yii::$app->authManager->getRole('root');
        Yii::$app->authManager->assign($role, $id);
    }

    public function revokeRole($role, $id)
    {
        return Yii::$app->authManager->revoke($role, $id);
    }


    public function setPasswordResetToken()
    {
        $this->password_reset_token_hash = Yii::$app->getSecurity()->generateRandomString();
    }

    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    public function getId()
    {
        return $this->id;
    }

    public function getEmail()
    {
        return $this->email;
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['auth_key' => $token]);
    }

    public static function findByPasswordResetToken($passwordReset)
    {
        return static::findOne(['password_reset_token_hash' => $passwordReset]);
    }

    public function getAuthKey()
    {
        return $this->auth_key;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public function validatePassword($password)
    {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password_hash);
    }

    public static function encodePassword($password)
    {
        return Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    /**
     * Finds administrator by email
     *
     * @param string $email
     * @return static
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email]);
    }

    /**
     * Finds administrator by id
     *
     * @param string $id
     * @return static
     */
    public static function findById($id)
    {
        return static::findOne(['id' => $id]);
    }

    /**
     * Finds administrator by id
     *
     * @return true||false
     */
    public function isRoot()
    {
        $roles = Yii::$app->authManager->getRolesByUser($this->id);
        $root = Yii::$app->authManager->getRole('root');
        foreach ($roles as $role)
            if ($role == $root)
                return true;
        return false;
    }
}

controllers/AdministratorController.php
<?php

namespace app\controllers;

use app\models\Companies;
use app\models\CompaniesSearch;
use yii;
use app\models\ActivateForm;
use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\ResetPasswordForm;
use app\models\RootResetPassword;
use app\models\SignUpForm;
use app\models\ValidateEmail;
use app\models\Administrator;
use app\models\AdministratorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\ForbiddenHttpException;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\AccessControl;

/**
 * AdministratorController implements the CRUD actions for Administrator model.
 */
class AdministratorController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'login', 'sign-up', 'password', 'update', 'delete', 'view', 'index', 'reset-password', 'root-reset-password', 'success', 'validate-email'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'sign-up', 'reset-password', 'success', 'validate-email'],
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'password', 'update', 'view', 'index',],
                        'allow' => true,
                        'roles' => ['admin', 'root'],
                    ],
                    [
                        'actions' => ['delete', 'root-reset-password',],
                        'allow' => true,
                        'roles' => ['root'],
                    ]

                ],

            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }


    public function actionActivate($token)
    {
        $model = new ActivateForm();

        if ($model->activate($token)) {
            return $this->render('success', ['success' => 'Activation is done.']);
        }

        return $this->render('error', ['error' => 'Activation is false.']);
    }

    public function actionValidateEmail()
    {
        $model = new ValidateEmail();
        if ($model->load(Yii::$app->request->post()) && $model->validateEmail()) {
            if ($model->sendEmail()) {
                return $this->render('success', ['success' => 'Check your email']);
            } else
                return $this->render('error', ['error' => 'Some problems']);
        }
        return $this->render('validate-email', ['model' => $model]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            return $this->render('success', ['success' => 'Your password is update']);
        }

        return $this->render('reset-password', ['model' => $model]);
    }

    public function actionRootResetPassword($slug)
    {
        $model = new RootResetPassword();

        if (!Yii::$app->user->can('canResetPassword', ['slug' => $slug]))
            throw new ForbiddenHttpException('Access denied.');

        if ($model->load(Yii::$app->request->post()) && $model->save($slug)) {
            return $this->redirect(['view', 'slug' => $slug]);
        }

        return $this->render('root-reset-password', ['model' => $model]);
    }

    public function actionUpdate($slug)
    {
        $model = $this->findModelBySlug($slug);
        $companies = CompaniesSearch::getArrayCompanies();
        $auth = Yii::$app->authManager;

        if (!Yii::$app->user->can('updateOwnProfile', ['slug' => $slug]))
            throw new ForbiddenHttpException('Access denied');

        if ($model->load(Yii::$app->request->post())) {
            if (Yii::$app->user->identity->isRoot()) {
                if ($model->group_role == 'root') {
                    $auth->revokeAll($model->id);
                    $auth->assign($auth->getRole('root'), $model->id);
                }

                if ($model->group_role == 'admin') {
                    $auth->revokeAll($model->id);
                    $auth->assign($auth->getRole('admin'), $model->id);
                }
            }
            if ($model->save()) {
                return $this->redirect(['view', 'slug' => $model->slug]);
            }
        }
        return $this->render('update', [
            'model' => $model,
            'companies' => $companies,
        ]);


    }

    public function actionIndex()
    {
        $searchModel = new AdministratorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    public function actionView($slug)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->render('view', [
                'model' => $this->findModelBySlug($slug),
            ]);
        } else {
            $model = new SignUpForm();
            return $this->render('sign-up', ['model' => $model]);
        }
    }

    /**
     * Creates a new Administrator model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionSignUp()
    {
        $model = new SignUpForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                $user->setRoleAdmin($user->id);
                if ($model->sendEmail($user->email)) {
                    return $this->render('success', ['success' => 'Activation message has been send. Please check your email.']);
                }
            }
        }
        return $this->render('sign-up', [
            'model' => $model,
        ]);
    }

    public function actionPassword($slug)
    {
        $model = new PasswordForm();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'slug' => $slug]);
        } else {
            return $this->render('password', ['model' => $model]);
        }
    }


    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goHome();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionDelete($slug)
    {
        $model = $this->findModelBySlug($slug);
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Administrator model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Administrator the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Administrator::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }


    protected function findModelBySlug($slug)
    {
        if (($model = Administrator::findOne(['slug' => $slug])) !== null)
            return $model;
        else
            throw new NotFoundHttpException("The requested page does not exist.");
    }
}

controllers/CompaniesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Companies;
use app\models\CompaniesSearch;
use yii\web\Controller;
use yii\web\NotAcceptableHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CompaniesController implements the CRUD actions for Companies model.
 */
class CompaniesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Companies models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CompaniesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Companies model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Companies model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        if (!Yii::$app->user->isGuest) {
            $company_id = Yii::$app->user->identity->company_id;
            if ($company_id == null) {
                $model = new Companies();

                if ($model->load(Yii::$app->request->post()) && $model->save()) {
                    return $this->redirect(['view', 'id' => $model->id]);
                } else {
                    return $this->render('create', [
                        'model' => $model,
                    ]);
                }
            } else {
                $model = $this->findModel($company_id);
                $this->redirect(['view', 'id' => $model->id]);
            }
        } else {
            $this->redirect(['administrator/login']);
        }
    }


    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->user->identity->company_id == $model->id) {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new NotAcceptableHttpException("This isn't your company");
        }
    }


    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->user->identity->company_id == $model->id) {
            $model->delete();
        } else {
            throw new NotAcceptableHttpException("This isn't your company");
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Companies model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Companies the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Companies::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/administrator/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $companies app\models\Companies */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="administrator-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>



    <?php if (Yii::$app->user->identity->isRoot()) {
        echo $form->field($model, 'company_id')->dropDownList($companies);
        echo $form->field($model, 'group_role')->dropDownList(['root' => 'root', 'admin' => 'admin']);
        echo $form->field($model, 'status')->dropDownList(['-1' => 'Blocked', '0' => 'In active', '1' => 'Active']);
    } ?>


    <?php if ($model->isNewRecord) { ?>

        <?= $form->field($model, 'password_hash')->passwordInput(['value' => '']) ?>
    <?php } ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Sign up' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

    <?php if (!Yii::$app->user->isGuest) { ?>
        <div class="form-group">
            <?= Html::a('Change password', ['password', 'slug' => $model->slug], ['class' => 'btn btn-default']) ?>

            <?php if (Yii::$app->user->identity->isRoot())  echo Html::a('Reset password', ['root-reset-password', 'slug' => $model->slug], ['class' => 'btn btn-warning']) ?>
        </div>
    <?php } ?>

</div>

views/administrator/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\AdministratorSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="administrator-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'surname') ?>

    <?= $form->field($model, 'slug') ?>

    <?= $form->field($model, 'company_id') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <?php // echo $form->field($model, 'access_token') ?>

    <?php // echo $form->field($model, 'password_hash') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/administrator/error.php
<?php
/**
 * Created by PhpStorm.
 * @author: Arsenii
 * Date: 20.06.16
 * Time: 15:50
 */
/* @var $error result of activate */
?>

<div class="alert alert-danger">
    <strong><?= $error ?></strong>
</div>

views/administrator/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\AdministratorSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Administrators';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="administrator-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php echo (Yii::$app->user->isGuest) ? Html::a('Sign Up', ['sign-up'], ['class' => 'btn btn-success'])
            : Html::a('Profile', Url::to(['view', 'slug' => Yii::$app->user->identity->slug]), ['class' => 'btn btn-success']) ?>

    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'name',
            'surname',
            'email',
            'company_id',
            'slug',
            ['class' => 'yii\grid\ActionColumn',
                'template' => '{view}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', Url::to(['view', 'slug' => $model->slug]));
                    },
/*                    'update' => function ($url, $model) {
                      return Html::a('<span class="glyphicon glyphicon-pencil"></span>', Url::to(['update', 'slug' => $model->slug]));
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'slug' => $model->slug], [
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]);
                    },*/
                ],
            ],
        ],
    ]); ?>
</div>

views/administrator/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?> or <?= Html::a('Sign up', ['sign-up'], ['class' => 'btn btn-default']) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe')->checkbox([
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ]) ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            <?= Html::a('Reset password', ['validate-email'], ['class' => 'btn btn-default']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
    
</div>

views/administrator/password.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
/* @var $model app\models\Administrator */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Update Password: ' . Yii::$app->user->identity->name;
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Yii::$app->user->identity->name, 'url' => ['view', 'slug' => Yii::$app->user->identity->slug]];
$this->params['breadcrumbs'][] = 'Change password';
?>

<div class="password-form">
    <?php $form = ActiveForm::begin(); ?>
    <?= $form->field($model, 'oldPass')->passwordInput() ?>
    <?= $form->field($model, 'newPass')->passwordInput() ?>
    <?= $form->field($model, 'repeatPass')->passwordInput() ?>
    <div class="form-group">
        <?= Html::submitButton('Change', ['class' => 'btn btn-success'])?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/administrator/reset-password.php
<?php
/**
 * Created by PhpStorm.
 * @author: Arsenii
 * Date: 20.06.16
 * Time: 17:15
 */
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \app\models\ResetPasswordForm */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-md-offset-4 col-md-3">
            <?php $form = ActiveForm::begin(['id' => 'reset-password']); ?>

            <?= $form->field($model, 'newPass')->passwordInput(['autofocus' => true]) ?>
            
            <?= $form->field($model, 'repeatPass')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/administrator/root-reset-password.php
<?php
/**
 * Created by PhpStorm.
 * @author: Arsenii
 * Date: 21.06.16
 * Time: 12:30
 */
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please choose your new password:</p>

    <div class="row">
        <div class="col-md-offset-4 col-md-3">
            <?php $form = ActiveForm::begin([
                'id' => 'root-reset-password',
                'options' => ['class' => 'form-horizontal'],
            ]); ?>

            <?= $form->field($model, 'newPassword')->passwordInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'repeatNewPassword')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Reset', ['class' => 'btn btn-warning']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/administrator/sign-up.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Administrator */

$this->title = 'Sign Up';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="sign-form">

    <?php $form = ActiveForm::begin([
        'id' => 'sign-up',
        'options' => ['class' => 'form-horizontal'],
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'surname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['']) ?>

    <div class="form-group">
        <?= Html::submitButton('Sign up', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/administrator/success.php
<?php
/**
 * Created by PhpStorm.
 * @author: Arsenii
 * Date: 20.06.16
 * Time: 15:50
 */
/* @var $success result of activate */
?>
<div class="alert alert-success">
    <strong><?= $success ?></strong>
</div>

views/administrator/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */
/* @var $companies app\models\Companies */

$this->title = 'Update Administrator: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'slug' => $model->slug]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="administrator-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'companies' => $companies
    ]) ?>

</div>

views/administrator/validate-email.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $model app\models\Administrator */
/* @var $form yii\widgets\ActiveForm */

$this->title = 'Reset password';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="password-form col-md-offset-4 col-md-3">
    <?php $form = ActiveForm::begin([
        'id' => 'validate-email',
        'options' => ['class' => 'form-horizontal'],
    ]); ?>
    <?= $form->field($model, 'email')->textInput() ?>
    <div class="form-group">
        <?= Html::submitButton('Reset', ['class' => 'btn btn-success']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

views/administrator/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Administrator */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Administrators', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="administrator-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if ((Yii::$app->user->identity->slug == $model->slug) || (Yii::$app->user->identity->isRoot())) { ?>
            <?= Html::a('Update', ['update', 'slug' => $model->slug], ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Delete', ['delete', 'slug' => $model->slug], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method' => 'post',
                ],
            ]) ?>
            <?php if (Yii::$app->user->identity->company_id == null) {
                echo Html::a('Create company', ['companies/create'], ['class' => 'btn btn-default']);
            } else {
                echo Html::a('View company', ['companies/view', 'id' => $model->company_id], ['class' => 'btn btn-default']);
            } ?>
        <?php } ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'surname',
            'slug',
            'company_id',
            'email:email',
            'group_role',
            'status',
        ],
    ]) ?>


</div>